# Generated by Django 5.0.7 on 2024-07-30 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='utente',
            managers=[
            ],
        ),
    ]
