# Generated by Django 5.0.7 on 2024-08-01 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_utente_managers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='peso',
        ),
        migrations.DeleteModel(
            name='weights',
        ),
    ]
