# Generated by Django 5.0.7 on 2024-08-01 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_delete_peso_delete_weights'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pesata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Peso', models.FloatField(blank=True, default=None)),
                ('DataInserimentoPeso', models.DateField()),
                ('idPaziente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
