# Generated by Django 5.0.7 on 2024-08-04 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_pesata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idDottore', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cure_dottore', to=settings.AUTH_USER_MODEL)),
                ('idPaziente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cure_paziente', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Dieta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('nome', models.CharField(blank=True, max_length=30)),
                ('id_medico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='IDMedico', to=settings.AUTH_USER_MODEL)),
                ('paziente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='IDPaziente', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('via', models.CharField(blank=True, max_length=50)),
                ('civico', models.IntegerField(blank=True)),
                ('citta', models.CharField(blank=True, max_length=30)),
                ('provincia', models.CharField(blank=True, max_length=2)),
                ('proprietario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dottoreStudio', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
