# Generated by Django 5.0.7 on 2024-08-04 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_cura_dieta_studio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Studio',
        ),
    ]
