# Generated by Django 5.0.7 on 2024-08-04 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_delete_studio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('via', models.CharField(blank=True, max_length=50)),
                ('civico', models.IntegerField(blank=True)),
                ('citta', models.CharField(blank=True, max_length=30)),
                ('provincia', models.CharField(blank=True, max_length=2)),
                ('medico', models.OneToOneField(limit_choices_to={'tipo_utente': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
