# Generated by Django 5.0.7 on 2024-08-04 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_studio'),
    ]

    operations = [
        migrations.AddField(
            model_name='cura',
            name='statoRichiesta',
            field=models.IntegerField(default=-1),
        ),
    ]
