# Generated by Django 5.0.7 on 2024-08-05 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alimento_pasto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appuntamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stato', models.IntegerField(default=-1)),
                ('data_ora', models.DateTimeField()),
                ('Dottore', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dott_app', to=settings.AUTH_USER_MODEL)),
                ('Paziente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paz_app', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
