# Generated by Django 3.2.12 on 2024-08-26 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_utente_foto_profilo'),
    ]

    operations = [
        migrations.AddField(
            model_name='alimento',
            name='categoria',
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
