# Generated by Django 3.2.12 on 2024-08-28 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alimento_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuntamento',
            name='stato',
            field=models.IntegerField(default=0),
        ),
    ]
