# Generated by Django 4.2.14 on 2024-09-04 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_auto_20240828_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dieta',
            name='nome',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
