# Generated by Django 4.2.14 on 2024-09-04 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_dieta_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utente',
            name='foto_profilo',
            field=models.ImageField(default='images/avatar-default.png', upload_to='images/'),
        ),
    ]
